#!/usr/bin/env bash

## launch wofi with alt config

STYLE="$HOME/.config/wofi/style.css"

if [[ $(pidof wofi) ]]; then
	pkill wofi
	exit 1
fi

wofi --show drun --width=25% --height=40% --prompt 'Search...' -I --style "${STYLE}"
