#!/usr/bin/env bash

## launch wofi with alt config

CONFIG="$HOME/.config/wofi/config"
STYLE="$HOME/.config/wofi/style.css"
COLORS="$HOME/.config/wofi/colors"

if [[ ! $(pidof wofi) ]]; then
	# wofi --show drun --width=40% --prompt 'Search...' --conf "${CONFIG}" --style "${STYLE}" --color "${COLORS}" --columns 2
	wofi --show drun --width=40% --prompt 'Search...' --columns 2 -I --style "${STYLE}"
else
	pkill wofi
fi
