#!/usr/bin/env bash

## launch wofi with alt config

STYLE="$HOME/.config/wofi/style.css"

if [[ ! $(pidof wofi) ]]; then
	wofi --show drun --width=25% --height=40% --prompt 'Search...' -I --style "${STYLE}"
else
	pkill wofi
fi
