#!/usr/bin/env bash

## launch swaync with alt config
CONFIG="$HOME/.config/swaync/config.json"
STYLE="$HOME/.config/swaync/style.css"


if [[ ! $(pidof swaync) ]]; then
    swaync -s "${STYLE}" -c "${CONFIG}"
fi
