#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(discord slack teams)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Apply themes
~/.config/hypr/scripts/gtkthemes-bkp &

# Custom start
flatpak run app.tuple.app &
discord &
emacs_start &
slack_start &
teams_start &
