#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(mpd polkit-gnome discord slack teams)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Apply themes
~/.config/hypr/scripts/gtkthemes-bkp &

# Start mpd
exec mpd &

# Custom start
flatpak run app.tuple.app &
webcord &
exec ~/Perso/script/teams_start.sh &
exec ~/Perso/script/slack_start.sh &
emacs_start &
