#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(mpd polkit-gnome discord slack teams)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof "${_prs}") ]]; then
		killall -9 "${_prs}"
	fi
done

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Apply themes
~/.config/hypr/scripts/gtkthemes-bkp &

# Start mpd
exec mpd &

# Custom start
flatpak run app.tuple.app &
flatpak run io.github.spacingbat3.webcord &
exec ~/Perso/script/teams_start.sh &
exec ~/Perso/script/slack_start.sh &
emacs_start &

# exec ~/Perso/script/git_config_by_day.sh &
