#!/usr/bin/env bash

## launch waybar with alt config

CONFIG="$HOME/.config/waybar/config"
STYLE="$HOME/.config/waybar/style.css"

# Kill already running process
killall waybar
killall inotifywait
killall inotifywatch

while true; do
    waybar --bar main-bar --log-level error --config "$CONFIG" --style "$STYLE" &
    inotifywait -e create,modify "$CONFIG" "$STYLE"
    pkill waybar
done

trap "killall waybar" EXIT
