#+title: Hyprland
#+AUTHOR Corentin ROY (JilkoniX)
#+PROPERTY: header-args :tangle hyprland.conf
#+STARTUP: showeverything

* TABLE OF CONTENT :TOC:
- [[#output][OUTPUT]]
  - [[#example][Example]]
  - [[#laptop-screen][Laptop Screen]]
  - [[#syadem-setup][Syadem Setup]]
  - [[#home-setup][Home Setup]]
  - [[#default-setup][Default Setup]]
  - [[#default-mirror-setup][Default Mirror Setup]]
- [[#startup][STARTUP]]
  - [[#desktop-portals][Desktop-Portals]]
  - [[#wallpaper][Wallpaper]]
  - [[#notifications][Notifications]]
  - [[#status-barwaybar][Status-Bar/Waybar]]
  - [[#startup-script][Startup Script]]
  - [[#blue-light][Blue-Light]]
  - [[#bluetooth][Bluetooth]]
  - [[#swayidle][Swayidle]]
  - [[#polkit][Polkit]]
  - [[#wal][Wal]]
  - [[#network-manager][Network-Manager]]
- [[#input][INPUT]]
- [[#general][GENERAL]]
- [[#group][GROUP]]
- [[#decoration][DECORATION]]
- [[#anmations][ANMATIONS]]
- [[#dwindle][DWINDLE]]
- [[#misc][MISC]]
- [[#gesture][GESTURE]]
- [[#window-rules][WINDOW RULES]]
  - [[#general-1][General]]
  - [[#applications-specific][Applications specific]]
- [[#keybindings][KEYBINDINGS]]
  - [[#variable][Variable]]
  - [[#terminal][Terminal]]
  - [[#apps][Apps]]
  - [[#wofi][Wofi]]
  - [[#misc-1][Misc]]
  - [[#some-nice-mouse-binds][Some nice mouse binds]]
  - [[#function-keys][Function keys]]
  - [[#screenshots][Screenshots]]
  - [[#image-to-text][Image To Text]]
  - [[#hyprland][Hyprland]]
  - [[#window-split-ratio][Window Split Ratio]]
  - [[#tab-cycle][Tab Cycle]]
  - [[#focus][Focus]]
  - [[#move][Move]]
  - [[#resize][Resize]]
  - [[#workspaces][Workspaces]]
  - [[#send-to-workspaces][Send to Workspaces]]
  - [[#scroll-through-existing-workspaces][Scroll Through Existing Workspaces]]
- [[#screen-sharing][SCREEN-SHARING]]

* OUTPUT
Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

~monitor = name,resolution,position,scale~
or
~monitor = desc:description_from_hyprctl_monitors,resolution,position,scale~

*Mirrored displays*
If you want to mirror a display, add a =,mirror,[NAME]= at the end of the monitor rule, examples:

~monitor = DP-3,1920x1080@60,0x0,1,mirror,DP-2~

** Example
~monitor = eDP-1,1920x1080@60,0x0,1~
~monitor = eDP-1,transform,0~
~monitor = eDP-1,addreserved,10,10,10,10~
~workspace = eDP-1,1~

** Laptop Screen
#+begin_src conf
monitor = eDP-1, 1920x1080@60, 0x0,1
workspace = eDP-1, 2
#+end_src

** Syadem Setup
#+begin_src conf
monitor = desc:AOC Q3279WG5B 0x0000652C, preferred, 1920x0, 1
monitor = desc:AOC U32E2WG6 QELM5JA000186, 2560x1440@60, 1920x0, 1
#+end_src

** Home Setup
#+begin_src conf
monitor = desc:Iiyama North America PL2390 11298JH100680, preferred, -1920x0, 1
#+end_src

** Default Setup
#+begin_src conf
monitor = ,preferred, auto, 1
workspace = HDMI-A-1, 1
#+end_src

** Default Mirror Setup
#+begin_src conf
# monitor = , preferred, auto, 1, mirror, eDP-1
#+end_src

* STARTUP
=dbus-update-activation-environment...= , =--user import-environment...= and the script called =desktop-portals=  are found online and known to save time on laggy app on start and other good behaviors

** Desktop-Portals
#+begin_src conf
exec-once = ~/.config/hypr/scripts/desktop-portals.sh
#+end_src

** Wallpaper
#+begin_src conf
exec-once = swww img ~/Pictures/wallpapers/nature-blue-simplist.jpg
exec-once = swww init; swww kill; swww init
#+end_src

** Notifications
#+begin_src conf
exec = ~/.config/hypr/scripts/notifications
#+end_src

** Status-Bar/Waybar
#+begin_src conf
exec-once = ~/.config/hypr/scripts/statusbar
#+end_src

** Startup Script
#+begin_src conf
exec-once = ~/.config/hypr/scripts/startup
#+end_src

** Blue-Light
#+begin_src conf
exec-once = hyprshade auto
#+end_src

** Bluetooth
Make sure you have installed =blueman=
#+begin_src conf
exec-once = blueman-applet
#+end_src

** Swayidle
+ Dim after 240sec decrease brightness
+ Send notification about the pc going to sleep after 300sec
+ Lock the screen after 360sec
+ Before sleep lock screen
#+begin_src conf
exec-once = swayidle -w \
            timeout 240 'brightnessctl --save; brightnessctl set 20%' \
            timeout 300 'notify-send "Going to sleep in less a minute"' \
            timeout 360 '~/.config/hypr/scripts/sleep' \
                resume 'brightnessctl --restore' \
            before-sleep '~/.config/hypr/scripts/lockscreen'
#+end_src

** Polkit
Be careful to use the appropriate =polkit= and the right =path=
#+begin_src conf
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#+end_src

** Wal
#+begin_src conf
exec-once = wal -R
#+end_src

** Network-Manager
#+begin_src conf
exec-once = nm-applet --indicator
#+end_src

* INPUT
Configure mouse and touchpad here
#+begin_src conf
input {
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    natural_scroll = 0
    force_no_accel = 0
    # repeat_rate =
    # repeat_delay =
    numlock_by_default = 1
}
#+end_src

* GENERAL
#+begin_src conf
source = ~/.cache/wal/colors-hyprland.conf

general {
    # main_mod = SUPER

    layout = dwindle

    sensitivity = 1.0 # for mouse cursor

    gaps_in = 3
    gaps_out = 7

    border_size = 4

    # Dracula Theme
    # col.active_border = rgb(bd93f9)
    # col.inactive_border = rgba(44475aaa)

    # Nord Theme
    # col.active_border = rgb(88c0d0)
    # col.inactive_border = rgba(44475aaa)

    # Theme from pywal
    col.active_border = $color1
    col.inactive_border = $color0

    # damage_tracking = full # leave it on full unless you hate your GPU and want to make it suffer
    apply_sens_to_raw = 0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)

    # Make the cursor disappear after 3 seconds
    cursor_inactive_timeout = 3
}
#+end_src

* GROUP
#+begin_src conf
group {
    # Dracula Theme
    # col.group_border = rgba(282a36dd)
    # col.group_border_active = rgb(bd93f9)

    # Nord Theme
    # col.border_active = rgb(88c0d0)
    # col.border_inactive = rgba(282a36dd)

    # Theme from pywal
    col.border_active = $color1
    col.border_inactive = $color0
}
#+end_src

* DECORATION
Decoration settings like Rounded Corners, Opacity, Blur, etc.

Your blur ="amount"= is =blur_size * blur_passes= , but high blur_size (over around 5-ish) will produce artifacts.
if you want heavy blur, you need to up the blur_passes.
the more passes, the more you can up the blur_size without noticing artifacts.

#+begin_src conf
decoration {
    rounding = 4       # Original: rounding = -1

    # Shadow
    drop_shadow = true
    shadow_range = 8
    shadow_offset = 1 2
    shadow_render_power = 3
    shadow_scale = 0.97

    col.shadow_inactive = 0x50000000
    col.shadow = rgba(1E202966)

    fullscreen_opacity=0.9

    blur {
        size = 5 # minimum 1
        passes = 2 # minimum 1, more passes = more resource intensive.

        ignore_opacity = false
    }

    # Dim
    dim_inactive = true
    dim_strength = 0.1
}
#+end_src


* ANMATIONS
#+begin_src conf
animations {
    enabled = 1

    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = fluent_decel, 0.1, 1, 0, 1
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1

    # Animation configs
    animation = windows, 1, 3, md3_decel, popin 60%
    animation = border, 1, 10, default
    animation = fade, 1, 2.5, md3_decel
    # animation = workspaces, 1, 3.5, md3_decel, slide
    animation = workspaces, 1, 3.5, easeOutExpo, slide
    # animation = workspaces, 1, 7, fluent_decel, slidefade 15%
    # animation = specialWorkspace, 1, 3, md3_decel, slidefadevert 15%
    animation = specialWorkspace, 1, 3, md3_decel, slidevert}
#+end_src

* DWINDLE
#+begin_src conf
dwindle {
    pseudotile = 0 # enable pseudotiling on dwindle
    preserve_split = true
    smart_split = false
}
#+end_src

* MISC
#+begin_src conf
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = false
}
#+end_src

* GESTURE
#+begin_src conf
gestures {
    workspace_swipe = yes
    workspace_swipe_fingers = 3
}
#+end_src

* WINDOW RULES
** General
#+begin_src conf

# Float Necessary Windows
windowrule = float,Wofi
windowrule = float,waypaper
windowrule = float,Tuple
windowrule = float,pavucontrol
windowrule = float,foot-float
windowrule = float,yad|nm-connection-editor|pavucontrolk
windowrule = float,polkit-gnome|kvantummanager|qt5ct
windowrule = float,feh|Viewnior|Gpicview|Gimp|nomacs
windowrule = float,VirtualBox Manager|qemu|Qemu-system-x86_64
windowrule = float,xfce4-appfinder

windowrulev2 = float,class:^()$,title:^(Picture in picture)$
windowrulev2 = float,class:^(brave)$,title:^(Save File)$
windowrulev2 = float,class:^(brave)$,title:^(Open File)$
windowrulev2 = float,class:^(brave-browser)$,title:^(Bitwarden - Brave)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(org.twosheds.iwgtk)$
windowrulev2 = float,class:^(blueberry.py)$
windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$

windowrule = float,foot-full
windowrule = move 0 0,foot-full
windowrule = size 100% 100%,foot-full

windowrule = float,wlogout
windowrule = move 0 0,wlogout
windowrule = size 100% 100%,wlogout
windowrule = animation slide,wlogout

#windowrule = move 69 420,abc
#windowrule = size 420 69,abc
#windowrule = tile,xyz
#windowrule = pseudo,abc
#windowrule = monitor 0,xyz
#windowrule = workspace 12,abc
#windowrule = opacity 1.0,abc
#windowrule = animation slide left,abc
#windowrule = rounding 10,abc
#+end_src

** Applications specific
#+begin_src conf
windowrule = opacity 0.90 override 0.90 override, .*
#+end_src

* KEYBINDINGS
** Variable
#+begin_src conf
$term = terminator
$term1 = kitty
$term2 = alacritty
$wallpapermenu = ~/.config/wofi/wallpaper.sh
$thememenu = ~/.config/wofi/theme.sh
$appmenu = ~/.config/hypr/scripts/menu
$menu3 = xfce4-appfinder
$powermenu = ~/.config/hypr/scripts/powermenu
$volume = ~/.config/hypr/scripts/volume
$backlight = ~/.config/hypr/scripts/brightness
$screenshot = ~/.config/hypr/scripts/screenshot
$lockscreen = ~/.config/hypr/scripts/lockscreen
$suspend = ~/.config/hypr/scripts/suspend
$wlogout = ~/.config/hypr/scripts/wlogout
$colorpicker = ~/.config/hypr/scripts/colorpicker
$files = thunar
$editor = emacsclient -c -n -a 'emacs'
# $editor-everywhere = emacsclient --eval "(emacs-everywhere)" -a "doom +everywhere"
$editor-everywhere = emacsclient --eval "(emacs-everywhere)"
$browser = brave
#+end_src

** Terminal
#+begin_src conf
bind = SUPER,Return,exec,$term2
bind = SUPERSHIFT,Return,exec,$term1
bind = SUPERALT,Return,exec,$term
#+end_src

** Apps
#+begin_src conf
bind = SUPERSHIFT,T,exec,$files
bind = SUPERSHIFT,E,exec,$editor
bind = SUPERSHIFT,I,exec,$editor-everywhere
bind = SUPERSHIFT,W,exec,$browser
bind = SUPERSHIFT,S,exec,XDG_CURRENT_DESKTOP="gnome" gnome-control-center
bind = CTRLSHIFT,Escape,exec,btop
bind = SUPERSHIFT,N,exec,swaync-client -t -sw
#+end_src

** Wofi
#+begin_src conf
bind = SUPER,D,exec,$appmenu
bind = SUPER,X,exec,$powermenu
bind = SUPER,W,exec,$wallpapermenu
bind = SUPER,T,exec,$thememenu
#+end_src

** Misc
#+begin_src conf
bind = SUPER,N,exec,nm-connection-editor
bind = SUPER,P,exec,$colorpicker
bind = CTRLALT,L,exec,$suspend
#+end_src

** Some nice mouse binds
#+begin_src conf
bindm = SUPER,mouse:272,movewindow
bindm = SUPER,mouse:273,resizewindow
#+end_src

** Function keys
#+begin_src conf
bind = ,XF86MonBrightnessUp,exec,$backlight --inc
bind = ,XF86MonBrightnessDown,exec,$backlight --dec
bind = ,XF86AudioRaiseVolume,exec,$volume --inc
bind = ,XF86AudioLowerVolume,exec,$volume --dec
bind = ,XF86AudioMute,exec,$volume --toggle
bind = ,XF86AudioMicMute,exec,$volume --toggle-mic
bind = ,XF86AudioNext,exec,playerctl next
bind = ,XF86AudioPrev,exec,playerctl previous
bind = ,XF86AudioPlay,exec,playerctl play-pause
bind = ,XF86AudioStop,exec,playerctl stop
#+end_src

** Screenshots
#+begin_src conf
bind = ,Print,exec,$screenshot --now
bind = CTRL,Print,exec,$screenshot --in5
bind = SHIFT,Print,exec,$screenshot --in10
bind = SUPER,Print,exec,$screenshot --win
bind = SUPERCTRL,Print,exec,$screenshot --area
#+end_src

** Image To Text
#+begin_src conf
bind = SUPERSHIFTCTRL,S,exec,grim -g "$(slurp -d -c D1E5F4BB -b 1B232866 -s 00000000)" "tmp.png" && tesseract "tmp.png" - | wl-copy && rm "tmp.png"
#+end_src

** Hyprland
#+begin_src conf
bind = SUPER,Q,killactive,
bind = CTRLALT,Delete,exit,
bind = SUPER,F,fullscreen, 0
bind = SUPERSHIFT,F,fullscreen,1
bind = SUPER,Space,togglefloating,
bind = SUPERSHIFT,Space,togglesplit,
bind = SUPER,S,pseudo,
bind = SUPER,O,toggleopaque
#+end_src

** Window Split Ratio
#+begin_src conf
binde = SUPERCTRL, Minus, splitratio, -0.1
binde = SUPERCTRL, Equal, splitratio, 0.1
#+end_src

** Tab Cycle
To switch between windows in a floating workspace

#+begin_src conf
bind = SUPER,Tab,cyclenext,          # change focus to another window
bind = SUPER,Tab,bringactivetotop,   # bring it to the top
#+end_src

** Focus
#+begin_src conf
bind = SUPER,H,movefocus,l
bind = SUPER,H,bringactivetotop
bind = SUPER,L,movefocus,r
bind = SUPER,L,bringactivetotop
bind = SUPER,K,movefocus,u
bind = SUPER,K,bringactivetotop
bind = SUPER,J,movefocus,d
bind = SUPER,J,bringactivetotop
#+end_src

** Move
#+begin_src conf
bind = SUPERSHIFT,H,movewindow,l
bind = SUPERSHIFT,L,movewindow,r
bind = SUPERSHIFT,K,movewindow,u
bind = SUPERSHIFT,J,movewindow,d
#+end_src

** Resize
#+begin_src conf
bind = SUPERCTRL,H,resizeactive,-20 0
bind = SUPERCTRL,L,resizeactive,20 0
bind = SUPERCTRL,K,resizeactive,0 -20
bind = SUPERCTRL,J,resizeactive,0 20
#+end_src

** Workspaces
#+begin_src conf
bind = SUPER,ampersand,workspace,1
bind = SUPER,eacute,workspace,2
bind = SUPER,quotedbl,workspace,3
bind = SUPER,apostrophe,workspace,4
bind = SUPER,parenleft,workspace,5
bind = SUPER,minus,workspace,6
bind = SUPER,egrave,workspace,7
bind = SUPER,underscore,workspace,8
#+end_src

** Send to Workspaces
#+begin_src conf
bind = ALT,ampersand,movetoworkspace,1
bind = ALT,eacute,movetoworkspace,2
bind = ALT,quotedbl,movetoworkspace,3
bind = ALT,apostrophe,movetoworkspace,4
bind = ALT,parenleft,movetoworkspace,5
bind = ALT,minus,movetoworkspace,6
bind = ALT,egrave,movetoworkspace,7
bind = ALT,underscore,movetoworkspace,8
#+end_src

** Scroll Through Existing Workspaces
#+begin_src conf
bind = SUPER,mouse_down,workspace,e+1
bind = SUPER,mouse_up,workspace,e-1

bind = ControlSuper, mouse_up, workspace, +1
bind = ControlSuper, mouse_down, workspace, -1
#+end_src


* SCREEN-SHARING
#+begin_src conf
env = GDK_BACKEND=wayland,x11
env = QT_QPA_PLATFORM="wayland;xcb"
env = XDG_CURRENT_DESKTOP=Hyprland
env = XDG_SESSION_TYPE=wayland
env = XDG_SESSION_DESKTOP=Hyprland

exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#+end_src
