#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

# THEME='Dracula'
# THEME='Nordic'
# THEME='adw-gtk3-dark'
THEME='Adwaita-dark'

ICONS='Papirus-Dark'
FONT='Noto Sans 9'
CURSOR='Bibata-Modern-Classic'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
