#!/usr/bin/env bash

CONFIG="$HOME/.config/rofi/config.rasi"

if [[ $(pidof rofi) ]]; then
    pkill rofi
    exit 1
fi
rofi -show combi -combi-modes "drun,window,run" -modes "combi,window,filebrowser" -show-icons -config "${CONFIG}"
