#!/usr/bin/env bash

CONFIG="$HOME/.config/rofi/config.rasi"

if [[ $(pidof rofi) ]]; then
    pkill rofi
    exit 1
fi
rofi -show drun -modes "window,drun,filebrowser" -show-icons -config "${CONFIG}"
