#!/bin/bash

hyprshot -m ${1:-region} --raw |
  satty --filename - \
    --output-filename ~/Pictures/screenshot-$(date +'%Y-%m-%d_%H-%M-%S').png \
    --early-exit \
    --actions-on-enter save-to-clipboard \
    --copy-command 'wl-copy'
