#!/usr/bin/env bash

## launch waybar with alt config
CONFIG="$HOME/.config/waybar/config_hyprland.json"
STYLE="$HOME/.config/waybar/style_hyprland.css"
CONFIG_FILES="$CONFIG $STYLE $HOME/.cache/wal/colors-waybar.css"

trap "killall waybar" EXIT

while true; do
    waybar --bar main-bar --log-level error --config "$CONFIG" --style "$STYLE" &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done

trap "killall waybar" EXIT
