#!/usr/bin/env bash

## launch waybar with alt config

CONFIG="$HOME/.config/waybar/config"
STYLE="$HOME/.config/waybar/style.css"
COLORS="$HOME/.cache/wal/colors-waybar.css"

# Kill already running process
killall inotifywait
killall inotifywatch
killall waybar

while true; do
    waybar --bar main-bar --log-level error --config "$CONFIG" --style "$STYLE" &
    inotifywait -e create,modify "$CONFIG" "$STYLE" "$COLORS"
    pkill waybar
done

trap "killall waybar" EXIT
