#+title: Hyprland
#+AUTHOR Corentin ROY (JilkoniX)
#+PROPERTY: header-args :tangle hyprland.conf
#+STARTUP: showeverything

* TABLE OF CONTENT :TOC:
- [[#monitor][MONITOR]]
  - [[#example][Example]]
  - [[#laptop-screen][Laptop Screen]]
  - [[#work-setup][Work Setup]]
  - [[#home-setup][Home Setup]]
  - [[#default-setup][Default Setup]]
- [[#startup][STARTUP]]
  - [[#desktop-portals][Desktop-Portals]]
  - [[#wallpaper][Wallpaper]]
  - [[#notifications][Notifications]]
  - [[#status-bar][Status-Bar]]
  - [[#startup-script][Startup Script]]
  - [[#blue-light][Blue-Light]]
  - [[#bluetooth][Bluetooth]]
  - [[#swayidle][Swayidle]]
  - [[#hypridle][Hypridle]]
  - [[#polkit][Polkit]]
  - [[#wal][Wal]]
  - [[#network-manager][Network-Manager]]
  - [[#clipboard][Clipboard]]
  - [[#gtk][Gtk]]
  - [[#hyprcursor][Hyprcursor]]
  - [[#ghostty][Ghostty]]
- [[#input][INPUT]]
- [[#general][GENERAL]]
- [[#cursor][CURSOR]]
- [[#group][GROUP]]
- [[#decoration][DECORATION]]
- [[#render][RENDER]]
- [[#anmations][ANMATIONS]]
- [[#dwindle][DWINDLE]]
- [[#master][MASTER]]
- [[#gesture][GESTURE]]
- [[#misc][MISC]]
- [[#window-rules][WINDOW RULES]]
- [[#layerrules][LAYERRULES]]
- [[#keybindings][KEYBINDINGS]]
  - [[#variable][Variable]]
  - [[#terminal][Terminal]]
  - [[#apps][Apps]]
  - [[#rofi][Rofi]]
  - [[#misc-1][Misc]]
  - [[#some-nice-mouse-binds][Some nice mouse binds]]
  - [[#function-keys][Function keys]]
  - [[#screenshots][Screenshots]]
  - [[#screencapture][Screencapture]]
  - [[#image-to-text][Image To Text]]
  - [[#status-bar-1][Status Bar]]
  - [[#hyprland][Hyprland]]
  - [[#end-active-session][End Active Session]]
  - [[#window-split-ratio][Window Split Ratio]]
  - [[#tab-cycle][Tab Cycle]]
  - [[#focus][Focus]]
  - [[#move-window][Move Window]]
  - [[#focus-group-window][Focus Group Window]]
  - [[#resize-window][Resize Window]]
  - [[#workspaces][Workspaces]]
  - [[#clipboard-1][Clipboard]]
  - [[#zoom][Zoom]]
  - [[#notification][Notification]]
- [[#screen-sharing][SCREEN-SHARING]]
- [[#defaul_apps][DEFAUL_APPS]]

* MONITOR
Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

~monitor = name,resolution,position,scale~
or
~monitor = desc:description_from_hyprctl_monitors,resolution,position,scale~

*Mirrored displays*
If you want to mirror a display, add a =,mirror,[NAME]= at the end of the monitor rule, examples:

~monitor = DP-3,1920x1080@60,0x0,1,mirror,DP-2~

** Example
~monitor = eDP-1,1920x1080@60,0x0,1~
~monitor = eDP-1,transform,0~
~monitor = eDP-1,addreserved,10,10,10,10~
~workspace = eDP-1,1~

** Laptop Screen
#+begin_src conf
  # monitor = eDP-1, 1920x1080@60, 0x0,1
  monitor = eDP-1, 2880x1800@60, 0x0,1.5
  workspace = 1, monitor:eDP-1
#+end_src

** Work Setup
#+begin_src conf
  monitor = desc:AOC Q3279WG5B 0x0000652C, preferred, 1920x0, 1
  monitor = desc:AOC U32E2WG6 QELM5JA000186, 3840x2160@60, 1920x0, 1.5, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98
  monitor = desc:AOC Q3279WG5B 0x000067FB, 2560x1440@60, 1920x0, 1
  monitor = desc:LG Electronics LG TV SSCR2 0x01010101, preferred, 1920x0, 1.5
#+end_src

** Home Setup
#+begin_src conf
  monitor = desc:Iiyama North America PL2390 11298JH100680, preferred, 1920x0, 1
  monitor = desc:Iiyama North America PL2390 11298JH100788, preferred, -1920x0, 1
#+end_src

** Default Setup
#+begin_src conf
  monitor = ,preferred, auto, 1
  # monitor = ,preferred, auto, 1, mirror, eDP-1 # Mirror
  workspace = 2, monitor:HDMI-A-1
#+end_src

* STARTUP
=dbus-update-activation-environment...= , =--user import-environment...= and the script called =desktop-portals=  are found online and known to save time on laggy app on start and other good behaviors

** Desktop-Portals
#+begin_src conf
exec-once = ~/.config/hypr/scripts/desktop-portals.sh
#+end_src

** Wallpaper
#+begin_src conf
exec-once = hyprpaper
#+end_src

** Notifications
#+begin_src conf
exec = ~/.config/hypr/scripts/notifications
#+end_src

** Status-Bar
#+begin_src conf
  exec-once = ~/.config/hypr/scripts/status_bar
#+end_src

** Startup Script
#+begin_src conf
source = ~/.config/hypr/exec.conf
#+end_src

** Blue-Light
Make sure you have installed =hyprshade=
#+begin_src conf
exec-once = hyprshade auto
#+end_src

** Bluetooth
Make sure you have installed =blueman=
#+begin_src conf
exec-once = blueman-applet
#+end_src

** Swayidle
+ Dim primary screen, after 240sec decrease brightness
+ Sleep, after 360sec
+ Before sleep lock screen
#+begin_src conf :tangle no
exec-once = swayidle -w timeout 240 'brightnessctl --save; brightnessctl set 5%' resume 'brightnessctl --restore' timeout 360 '~/.config/hypr/scripts/sleep' before-sleep 'hyprlock'
#+end_src

** Hypridle
#+begin_src conf
exec-once = hypridle
#+end_src

** Polkit
Be careful to use the appropriate =polkit= and the right =path=
#+begin_src conf :tangle no
  # exec-once=/usr/lib/polkit-1/polkitd
#+end_src

#+begin_src conf
  exec-once=/usr/lib/polkit-kde-authentication-agent-1
#+end_src

** Wal
#+begin_src conf
exec-once = wal -R
#+end_src

** Network-Manager
Make sure you havc installed =network-manager-applet=
#+begin_src conf
exec-once = nm-applet --indicator
#+end_src

** Clipboard
#+begin_src conf
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
#+end_src

** Gtk
#+begin_src conf :tangle no
exec-once = ~/.config/hypr/scripts/gtkthemes-bkp
#+end_src

** Hyprcursor
#+begin_src conf
exec-once = hyprctl setcursor Qogir-dark 24 #19
#+end_src

** Ghostty
#+begin_src conf
exec-once = ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false
#+end_src

* INPUT
Configure mouse and touchpad here
#+begin_src conf
  input {
      kb_layout = fr
      # kb_variant =
      # kb_model =
      # kb_options =
      # kb_rules =
      follow_mouse = 1
      numlock_by_default = 1

      touchpad {
          natural_scroll = no
          scroll_factor = 0.8
          # Use two-finger clicks for right-click instead of lower-right corner
          clickfinger_behavior = 1
      }

      # Sensitity for mouse/trackpack
      sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  }
#+end_src

* GENERAL
#+begin_src conf
  source = ~/.cache/wal/colors-hyprland.conf

  general {
      gaps_in = 5
      gaps_out = 10
      border_size = 2
      layout = master
      col.active_border = $color4 $color6 45deg
      col.inactive_border = $color8
      allow_tearing = false
      snap {
          enabled = true
      }
      resize_on_border = true
  }
#+end_src

* CURSOR
Make the cursor disappear after 3 seconds
#+begin_src conf
  cursor {
    inactive_timeout = 3
    enable_hyprcursor = true
  }
#+end_src

* GROUP
#+begin_src conf
  group {
      col.border_active = $color4 $color6 45deg
      col.border_inactive = $color8

      groupbar {
         render_titles = false
         gradients = true
         height = 4
         col.active = $color4
         col.inactive = $color0
      }
  }
#+end_src

* DECORATION
Decoration settings like Rounded Corners, Opacity, Blur, etc.

Your blur =amount= is =blur_size * blur_passes= , but high blur_size (over around 5-ish) will produce artifacts.
if you want heavy blur, you need to up the blur_passes.
the more passes, the more you can up the blur_size without noticing artifacts.

#+begin_src conf
  decoration {
      active_opacity = 0.90
      inactive_opacity = 0.90
      rounding = 0         # original 10
      # rounding_power = 2.0  # original 2.0
      blur {
          enabled = true
          new_optimizations = true
          size = 6   # minimum 1
          passes = 2 # minimum 1, more passes = more resource intensive.
      }
      shadow {
          enabled = false
          range = 8
          offset = 1 2
          scale = 0.97
          color = rgba(1E202966)
          color_inactive = 0x50000000
      }
      dim_inactive = true
      dim_strength = 0.05
  }
#+end_src

* RENDER
#+begin_src conf
  render {
      cm_enabled = true # default value
  }
#+end_src


* ANMATIONS
#+begin_src conf
   animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.38, 0.04, 1, 0.07
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = softAcDecel, 0.26, 0.26, 0.15, 1
    bezier = md2, 0.4, 0, 0.2, 1 # use with .2s duration

    animation = windows, 1, 3, softAcDecel
    animation = windowsIn, 1, 3, md3_decel, popin 0%
    animation = windowsOut, 1, 3, md3_accel, popin 0%
    animation = border, 1, 10, default
    animation = fade, 1, 3, md3_decel
    animation = layersIn, 1, 3, md2, popin
    animation = layersOut, 1, 3, md2, popin
    animation = workspaces, 1, 2, md3_standard, slide
    animation = specialWorkspace, 1, 3, md3_decel, slidevert
}
#+end_src

* DWINDLE
#+begin_src conf
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
}
#+end_src

* MASTER
#+begin_src conf
master {
    new_on_top = false
}
#+end_src

* GESTURE
#+begin_src conf
gestures {
    workspace_swipe = yes
    workspace_swipe_fingers = 3
    workspace_swipe_create_new = true
}
#+end_src

* MISC
#+begin_src conf
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = false
}
#+end_src

* WINDOW RULES
List of options
- windowrule = move 69 420,abc
- windowrule = size 420 69,abc
- windowrule = tile,xyz
- windowrule = pseudo,abc
- windowrule = monitor 0,xyz
- windowrule = workspace 12,abc
- windowrule = opacity 1.0,abc
- windowrule = animation slide left,abc
- windowrule = rounding 10,abc

#+begin_src conf
  # Float Necessary Windows
  windowrule = float,class:^waypaper$
  windowrule = float,class:^org.pulseaudio.pavucontrol$
  windowrule = float,class:^Wiremix$
  windowrule = float,class:^foot-float$
  windowrule = float,class:^nm-connection-editor$
  windowrule = float,class:^Gimp$
  windowrule = float,class:^blueman-manager$
  windowrule = float,class:^org.twosheds.iwgtk$
  windowrule = float,class:^blueberry.py$
  windowrule = float,class:^(xdg-desktop-portal-gtk|org.freedesktop.impl.portal.desktop.kde)$
  windowrule = center, class:^(org.freedesktop.impl.portal.desktop.kde)$
  windowrule = size 1280 720,class:^(org.freedesktop.impl.portal.desktop.kde)$
  windowrule = size 700 500 class:^(org.pulseaudio.pavucontrol|Wiremix)$

  windowrule = float,class:^org.kde.gwenview$
  windowrule = size 65% 65%,class:^org.kde.gwenview$

  windowrule = float,class:^kitty$ title:^(float-.*)$
  windowrule = size 50% 50%,class:^kitty$ title:^(float-.*)$

  windowrule = workspace 4,class:^Pop$

  # Gnome Settings
  windowrule = float,class:^(org.gnome.Settings)$
  windowrule = center,class:^(org.gnome.Settings)$
  windowrule = size 1280 720,class:^(org.gnome.Settings)$

  # Browser
  windowrule = workspace 2,class:^brave-browser$
  windowrule = workspace 2,class:^zen$
  windowrule = float,class:^(brave)$,title:^(Open File)$
  windowrule = float,class:^(brave)$,title:^(Save File)$
  windowrule = float,class:^(brave)$,title:^(Picture in picture)$
  windowrule = float,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = size 740 440,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = move onscreen 100%-w-20,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = float,class:^brave-.*-Default$

  # Emacs
  windowrule = workspace 3,class:^(emacs)$

  # Message App
  windowrule = workspace 1,class:^(.*Microsoft Teams.*|teams-for-linux|discord|WebCord|Slack)$
  windowrule = workspace 1,class:^()$

  # All
  windowrule = opaque 1,class:^(.*)$
  windowrule = opaque 0,class:^(kitty|Alacritty|com.mitchellh.ghostty)$
#+end_src

* LAYERRULES
#+begin_src conf
  layerrule = noanim, selection
  layerrule = noanim, hyprpicker
  layerrule = dimaround, rofi
  layerrule = animation slide, swaync-control-center
#+end_src

* KEYBINDINGS
- ~d~ flag for description

** Variable
#+begin_src conf
  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  $mainMod = SUPER

  $term = ghostty --gtk-single-instance=true
  $termapp = $term -e
  $term2 = kitty
  $wallpapermenu = ~/.config/rofi/wallpaper.sh
  $thememenu = ~/.config/rofi/theme.sh
  $appmenu = ~/.config/rofi/appmenu.sh
  $clipboardlist = ~/.config/rofi/clipboardlist.sh
  $powermenu = ~/.config/hypr/scripts/powermenu
  $volume = ~/.config/hypr/scripts/volume
  $notificationmenu = swaync-client -t
  $brightness = ~/.config/hypr/scripts/brightness
  $lockscreen = hyprlock
  $sleep = ~/.config/hypr/scripts/sleep
  $suspend = ~/.config/hypr/scripts/suspend
  $wlogout = ~/.config/hypr/scripts/wlogout
  $colorpicker = ~/.config/hypr/scripts/colorpicker
  $files = dolphin
  $editor = emacsclient -c -n -a 'emacs'
  $editor-term = $term -e emacsclient -t -a 'emacs -nw'
  $editor-everywhere = emacsclient --eval "(emacs-everywhere)"
  $browser = zen
  $help_keybind = ~/.config/hypr/scripts/show_keybind
  $screenshot = ~/.config/hypr/scripts/screenshot
#+end_src

** Terminal
#+begin_src conf
  bindd = $mainMod, Return, Launch Terminal, exec, $term
  bindd = $mainMod SHIFT, Return, Launch Second Terminal, exec, $term2
  bindd = $mainMod CTRL, Return, Launch Floating Terminal, exec, [float; size 50% 60%] $term
#+end_src

** Apps
#+begin_src conf
  bindd = $mainMod, E, Launch File Manager, exec, $files
  bindd = $mainMod SHIFT, E, Launch Editor , exec, $editor
  bindd = $mainMod CTRL, E, Launch Terminal Editor, exec, $editor-term
  bindd = $mainMod SHIFT, I, Launch Editor Popup, exec, $editor-everywhere
  bindd = $mainMod SHIFT, W, Launch Browser, exec, $browser
  bindd = $mainMod, ccedilla, Launch K9s, exec, $termapp k9s
  bindd = $mainMod, m, Launch Btop, exec, $termapp btop
#+end_src

** Rofi
#+begin_src conf
  bindd = $mainMod, D, Launch AppMenu, exec, $appmenu
  bindd = $mainMod, X, Launch PowerMenu, exec, $powermenu
  bindd = $mainMod, W, Launch WallpaperMenu, exec, $wallpapermenu
  bindd = $mainMod, T, Launch ThemeMenu, exec, $thememenu
  bindd = $mainMod SHIFT, Comma, Launch HelpMenu, exec, pkill rofi || $help_keybind
#+end_src

** Misc
#+begin_src conf
bindd = $mainMod, C, ColorPicker, exec, $colorpicker
bindd = CTRL ALT,L, Suspend, exec, $suspend
#+end_src

** Some nice mouse binds
#+begin_src conf
bindmd = SUPER, mouse:272, MoveWindow, movewindow
bindmd = SUPER, mouse:273, ResizeWindow, resizewindow
#+end_src

** Function keys
- ~e~ flag is used to repeat cmd when hold
#+begin_src conf
  bindeld = ,XF86MonBrightnessUp, Raise Brightness, exec, $brightness --inc
  bindeld = ,XF86MonBrightnessDown, Lower Brightness, exec, $brightness --dec

  binded = , XF86AudioRaiseVolume, Raise Volume, exec, $volume --inc
  binded = , XF86AudioLowerVolume, Lower Volume, exec, $volume --dec
  bindd = , XF86AudioMute, Toggle Volume, exec, $volume --toggle
  bindd = , XF86AudioMicMute, Toggle Mic , exec, $volume --toggle-mic

  bindld = , XF86AudioNext, Next Track, exec, playerctl next
  bindld = , XF86AudioPause, Pause Media, exec, playerctl play-pause
  bindld = , XF86AudioPlay, Pause Media, exec, playerctl play-pause
  bindld = , XF86AudioPrev, Previous Track, exec, playerctl previous
  bindld = , XF86AudioStop, Stop Track, exec, playerctl stop
#+end_src

** Screenshots
#+begin_src conf
  bindd = , PRINT, Screenshot a Region, exec, $screenshot
  bindd = SHIFT, PRINT, Screenshot a Window, exec, $screenshot window
  bindd = CTRL, PRINT, Screenshot a Desktop, exec, $screenshot output
#+end_src

** Screencapture
#+begin_src conf
  bindd = $mainMod CTRL, S, Start Capture, exec, ~/.config/hypr/scripts/screen-capture.sh
#+end_src

** Image To Text
#+begin_src conf
  bindd = $mainMod SHIFT, T, Image to Text, exec, grim -g "$(slurp -d -c D1E5F4BB -b 1B232866 -s 00000000)" "tmp.png" && tesseract "tmp.png" - | wl-copy && rm "tmp.png"
#+end_src

** Status Bar
#+begin_src conf
  bindd = $mainMod SHIFT, W, Toggle Waybar, exec, pkill -SIGUSR1 waybar
#+end_src

** Hyprland
#+begin_src conf
  bindd = $mainMod, Q, Kill Active, killactive,
  bindd = $mainMod, F, Fullscreen, fullscreen, 2
  bindd = $mainMod CTRL, F, Fullscreen complete, fullscreen, 0
  bindd = $mainMod SHIFT, F, Fullscreen Window in Workspace, fullscreen, 1
  bindd = $mainMod, SPACE, Toggle Floating, togglefloating,
  bindd = $mainMod SHIFT, SPACE, ToggleSplit, togglesplit, # dwindle
  bindd = $mainMod, P, Pseudo Window, pseudo, # dwindle
  bindd = $mainMod, O, Toggle Opacity, exec, hyprctl dispatch setprop active opaque toggle
  bindd = $mainMod CTRL, SPACE, Pin Window, pin
  bindd = $mainMod, G, Toggle Group, togglegroup
  bindd = $mainMod SHIFT, C, Enable CompactMode, exec, ~/.config/hypr/scripts/compactmode.sh
  bindd = $mainMod, F1, Enable GameMode, exec, ~/.config/hypr/scripts/gamemode.sh
  bindd = $mainMod ALT, apostrophe, Switch Layout, exec, hyprctl keyword general:layout "$(hyprctl getoption general:layout | grep -q 'dwindle' && echo 'master' || echo 'dwindle')" #! @description: "Toggle between dwindle and master layout"; @windows;

  # Example special workspace (scratchpad)

  bindd = $mainMod, S, Toggle Magic Workspace, togglespecialworkspace, magic
  bindd = $mainMod SHIFT, S, Move Window to Magic Workspace, movetoworkspace, special:magic
#+end_src

** End Active Session
#+begin_src conf
  bindd = $mainMod, ESCAPE, Lock, exec, hyprlock
  bindd = $mainMod SHIFT, ESCAPE, Suspend, exec, systemctl suspend
  bindd = $mainMod ALT, ESCAPE, Exit, exit,
  bindd = $mainMod CTRL, ESCAPE, Reboot, exec, reboot
  bindd = $mainMod SHIFT CTRL, ESCAPE, Poweroff, exec, systemctl poweroff
#+end_src

** Window Split Ratio
#+begin_src conf
  bindd = $mainMod CTRL, Minus, Decrease ratio, splitratio, -0.1
  bindd = $mainMod CTRL, Equal, Increase ratio, splitratio, 0.1
#+end_src

** Tab Cycle
To switch between windows in a floating workspace

#+begin_src conf
  bindd = $mainMod, Tab, Cyclenext, cyclenext, # change focus to another window
  bindd = $mainMod, Tab, Bring Active to Top, bringactivetotop, # bring it to the top
#+end_src

** Focus
#+begin_src conf
  bindd = $mainMod, H, Move Focus Left, movefocus, l
  bindd = $mainMod, H, Bring Active to Top, bringactivetotop

  bindd = $mainMod, L, Move Focus Right, movefocus, r
  bindd = $mainMod, L, Bring Active to Top, bringactivetotop

  bindd = $mainMod, K, Move Focus Up, movefocus, u
  bindd = $mainMod, K, Bring Active to Top, bringactivetotop

  bindd = $mainMod, J, Move Focus Down, movefocus, d
  bindd = $mainMod, J, Bring Active to Top, bringactivetotop

  bindd = $mainMod, Semicolon, Focus Next Monitor, focusmonitor, +1
  bindd = $mainMod, Comma, Focus Prev Monitor, focusmonitor, -1
#+end_src

** Move Window
#+begin_src conf
  bindd = $mainMod SHIFT, H, Move window or group left, movewindoworgroup, l
  bindd = $mainMod SHIFT, L, Move window or group right, movewindoworgroup, r
  bindd = $mainMod SHIFT, K, Move window or group upper, movewindoworgroup, u
  bindd = $mainMod SHIFT, J, Move window or group lower, movewindoworgroup, d
#+end_src

** Focus Group Window
#+begin_src conf
  bindd = $mainMod, B,Previous in group, changegroupactive, b
  bindd = $mainMod SHIFT, B, Next in group, changegroupactive, f
#+end_src

** Resize Window
- 'e' flag is used to repeat cmd when hold
#+begin_src conf
  binded = $mainMod CTRL, H, Shrink Window Horizontally, resizeactive, -40 0
  binded = $mainMod CTRL, L, Grow Window Horizontally, resizeactive, 40 0
  binded = $mainMod CTRL, K, Shrink Window Vertically, resizeactive, 0 -40
  binded = $mainMod CTRL, J, Grow Window Vertically, resizeactive, 0 40
#+end_src

** Workspaces
*** Focus
#+begin_src conf
  bindd = $mainMod, ampersand, Focus workspace 1, workspace, 1
  bindd = $mainMod, eacute, Focus workspace 2, workspace, 2
  bindd = $mainMod, quotedbl, Focus workspace 3, workspace, 3
  bindd = $mainMod, apostrophe, Focus workspace 4, workspace, 4
  bindd = $mainMod, parenleft, Focus workspace 5, workspace, 5
  bindd = $mainMod, minus, Focus workspace 6, workspace, 6
  bindd = $mainMod, egrave, Focus workspace 7, workspace, 7
  bindd = $mainMod, underscore, Focus workspace 8, workspace, 8
#+end_src

*** Focus On Current Monitor
#+begin_src conf :tangle no
  bindd = $mainMod, ampersand, Focus Workspace on Current Monitor 1, focusworkspaceoncurrentmonitor, 1
  bindd = $mainMod, eacute, Focus Workspace on Current Monitor 2, focusworkspaceoncurrentmonitor, 2
  bindd = $mainMod, quotedbl, Focus Workspace on Current Monitor 3, focusworkspaceoncurrentmonitor, 3
  bindd = $mainMod, apostrophe, Focus Workspace on Current Monitor 4, focusworkspaceoncurrentmonitor, 4
  bindd = $mainMod, parenleft, Focus Workspace on Current Monitor 5, focusworkspaceoncurrentmonitor, 5
  bindd = $mainMod, minus, Focus Workspace on Current Monitor 6, focusworkspaceoncurrentmonitor, 6
  bindd = $mainMod, egrave, Focus Workspace on Current Monitor 7, focusworkspaceoncurrentmonitor, 7
  bindd = $mainMod, underscore, Focus Workspace on Current Monitor 8, focusworkspaceoncurrentmonitor, 8
#+end_src

*** Move workspace to different monitor
#+begin_src conf
  bindd = $mainMod ALT, h, Move workspace to right monitor, movecurrentworkspacetomonitor,l
  bindd = $mainMod ALT, j, Move workspace to lower monitor, movecurrentworkspacetomonitor,p
  bindd = $mainMod ALT, k, Move workspace to upper monitor, movecurrentworkspacetomonitor,u
  bindd = $mainMod ALT, l, Move workspace to right monitor, movecurrentworkspacetomonitor,r
#+end_src

*** Send to Workspaces
#+begin_src conf
  bindd = $mainMod SHIFT, ampersand, Move to workspace 1, movetoworkspace, 1
  bindd = $mainMod SHIFT, eacute, Move to workspace 2, movetoworkspace, 2
  bindd = $mainMod SHIFT, quotedbl, Move to workspace 3, movetoworkspace, 3
  bindd = $mainMod SHIFT, apostrophe, Move to workspace 4, movetoworkspace, 4
  bindd = $mainMod SHIFT, parenleft, Move to workspace 5, movetoworkspace, 5
  bindd = $mainMod SHIFT, minus, Move to workspace 6, movetoworkspace, 6
  bindd = $mainMod SHIFT, egrave, Move to workspace 7, movetoworkspace, 7
  bindd = $mainMod SHIFT, underscore, Move to workspace 8, movetoworkspace, 8
#+end_src

*** Send to Worspace silently
#+begin_src conf
  bindd = $mainMod CTRL, ampersand, Move workspace 1 silently, movetoworkspacesilent, 1
  bindd = $mainMod CTRL, eacute, Move workspace 2 silently, movetoworkspacesilent, 2
  bindd = $mainMod CTRL, quotedbl, Move workspace 3 silently, movetoworkspacesilent, 3
  bindd = $mainMod CTRL, apostrophe, Move workspace 4 silently, movetoworkspacesilent, 4
  bindd = $mainMod CTRL, parenleft, Move workspace 5 silently, movetoworkspacesilent, 5
  bindd = $mainMod CTRL, minus, Move workspace 6 silently, movetoworkspacesilent, 6
  bindd = $mainMod CTRL, egrave, Move workspace 7 silently, movetoworkspacesilent, 7
  bindd = $mainMod CTRL, underscore, Move workspace 8 silently, movetoworkspacesilent, 8
#+end_src

** Clipboard
#+begin_src conf
  bindd = SUPER, V, Open clipboard, exec, $clipboardlist
#+end_src

** Zoom
#+begin_src conf
  bindd = $mainMod, mouse_down, Zoom in, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 + 0.5}')
  bindd = $mainMod, mouse_up, Zoom out, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 - 0.5}')

  binded = $mainMod, equal, Zoom in, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 + 0.5}')
  binded = $mainMod SHIFT, equal, Zoom out, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 - 0.5}')
  bindd = $mainMod, agrave, Zoom reset, exec, hyprctl -q keyword cursor:zoom_factor 1

#+end_src

** Notification
#+begin_src conf
  bindd = $mainMod, N, Open Notifications, exec, $notificationmenu
#+end_src

* SCREEN-SHARING
#+begin_src conf
  env = GDK_BACKEND,wayland
  env = QT_QPA_PLATFORM,wayland
  env = XDG_CURRENT_DESKTOP,Hyprland
  env = XDG_SESSION_TYPE,wayland
  env = XDG_SESSION_DESKTOP,Hyprland
  env = QT_STYLE_OVERRIDE,kvantum
  env = SDL_VIDEODRIVER,wayland
  env = MOZ_ENABLE_WAYLAND,1
  env = ELECTRON_OZONE_PLATFORM_HINT,wayland
  env = OZONE_PLATFORM,wayland

  exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#+end_src

* DEFAUL_APPS
To activate default app for dolphin
#+begin_src conf
  env = XDG_MENU_PREFIX,arch-
#+end_src
