#+title: Hyprland
#+AUTHOR Corentin ROY (JilkoniX)
#+PROPERTY: header-args :tangle hyprland.conf
#+STARTUP: showeverything

* TABLE OF CONTENT :TOC:
- [[#monitor][MONITOR]]
  - [[#example][Example]]
  - [[#laptop-screen][Laptop Screen]]
  - [[#work-setup][Work Setup]]
  - [[#home-setup][Home Setup]]
  - [[#default-setup][Default Setup]]
- [[#startup][STARTUP]]
  - [[#desktop-portals][Desktop-Portals]]
  - [[#wallpaper][Wallpaper]]
  - [[#notifications][Notifications]]
  - [[#status-bar][Status-Bar]]
  - [[#startup-script][Startup Script]]
  - [[#blue-light][Blue-Light]]
  - [[#bluetooth][Bluetooth]]
  - [[#swayidle][Swayidle]]
  - [[#hypridle][Hypridle]]
  - [[#polkit][Polkit]]
  - [[#wal][Wal]]
  - [[#network-manager][Network-Manager]]
  - [[#clipboard][Clipboard]]
  - [[#gtk][Gtk]]
  - [[#hyprcursor][Hyprcursor]]
  - [[#ghostty][Ghostty]]
- [[#input][INPUT]]
- [[#general][GENERAL]]
- [[#cursor][CURSOR]]
- [[#group][GROUP]]
- [[#decoration][DECORATION]]
- [[#render][RENDER]]
- [[#anmations][ANMATIONS]]
- [[#dwindle][DWINDLE]]
- [[#master][MASTER]]
- [[#gesture][GESTURE]]
- [[#misc][MISC]]
- [[#window-rules][WINDOW RULES]]
- [[#layerrules][LAYERRULES]]
- [[#keybindings][KEYBINDINGS]]
  - [[#variable][Variable]]
  - [[#terminal][Terminal]]
  - [[#apps][Apps]]
  - [[#rofi][Rofi]]
  - [[#misc-1][Misc]]
  - [[#some-nice-mouse-binds][Some nice mouse binds]]
  - [[#function-keys][Function keys]]
  - [[#screenshots][Screenshots]]
  - [[#image-to-drawapp][Image To DrawApp]]
  - [[#screencapture][Screencapture]]
  - [[#image-to-text][Image To Text]]
  - [[#status-bar-1][Status Bar]]
  - [[#hyprland][Hyprland]]
  - [[#end-active-session][End Active Session]]
  - [[#window-split-ratio][Window Split Ratio]]
  - [[#tab-cycle][Tab Cycle]]
  - [[#focus][Focus]]
  - [[#move-window][Move Window]]
  - [[#focus-group-window][Focus Group Window]]
  - [[#resize-window][Resize Window]]
  - [[#workspaces][Workspaces]]
  - [[#clipboard-1][Clipboard]]
  - [[#zoom][Zoom]]
  - [[#notification][Notification]]
- [[#screen-sharing][SCREEN-SHARING]]
- [[#defaul_apps][DEFAUL_APPS]]

* MONITOR
Configure your Display resolution, offset, scale and Monitors here, use `hyprctl monitors` to get the info.

~monitor = name,resolution,position,scale~
or
~monitor = desc:description_from_hyprctl_monitors,resolution,position,scale~

*Mirrored displays*
If you want to mirror a display, add a =,mirror,[NAME]= at the end of the monitor rule, examples:

~monitor = DP-3,1920x1080@60,0x0,1,mirror,DP-2~

** Example
~monitor = eDP-1,1920x1080@60,0x0,1~
~monitor = eDP-1,transform,0~
~monitor = eDP-1,addreserved,10,10,10,10~
~workspace = eDP-1,1~

** Laptop Screen
#+begin_src conf
  # monitor = eDP-1, 1920x1080@60, 0x0,1
  monitor = eDP-1, 2880x1800@60, 0x0,1.5
  workspace = 1, monitor:eDP-1
#+end_src

** Work Setup
#+begin_src conf
  monitor = desc:AOC Q3279WG5B 0x0000652C, preferred, 1920x0, 1
  monitor = desc:AOC U32E2WG6 QELM5JA000186, 3840x2160@60, 1920x0, 1.5, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98
  monitor = desc:AOC Q3279WG5B 0x000067FB, 2560x1440@60, 1920x0, 1
  monitor = desc:LG Electronics LG TV SSCR2 0x01010101, preferred, 1920x0, 1.5
#+end_src

** Home Setup
#+begin_src conf
  monitor = desc:Iiyama North America PL2390 11298JH100680, preferred, 1920x0, 1
  monitor = desc:Iiyama North America PL2390 11298JH100788, preferred, -1920x0, 1
#+end_src

** Default Setup
#+begin_src conf
  monitor = ,preferred, auto, 1
  # monitor = ,preferred, auto, 1, mirror, eDP-1 # Mirror
  workspace = 2, monitor:HDMI-A-1
#+end_src

* STARTUP
=dbus-update-activation-environment...= , =--user import-environment...= and the script called =desktop-portals=  are found online and known to save time on laggy app on start and other good behaviors

** Desktop-Portals
#+begin_src conf
exec-once = ~/.config/hypr/scripts/desktop-portals.sh
#+end_src

** Wallpaper
#+begin_src conf
exec-once = hyprpaper
#+end_src

** Notifications
#+begin_src conf
exec = ~/.config/hypr/scripts/notifications
#+end_src

** Status-Bar
#+begin_src conf
  exec-once = ~/.config/hypr/scripts/status_bar
#+end_src

** Startup Script
#+begin_src conf
source = ~/.config/hypr/exec.conf
#+end_src

** Blue-Light
Make sure you have installed =hyprshade=
#+begin_src conf
exec-once = hyprshade auto
#+end_src

** Bluetooth
Make sure you have installed =blueman=
#+begin_src conf
exec-once = blueman-applet
#+end_src

** Swayidle
+ Dim primary screen, after 240sec decrease brightness
+ Sleep, after 360sec
+ Before sleep lock screen
#+begin_src conf :tangle no
exec-once = swayidle -w timeout 240 'brightnessctl --save; brightnessctl set 5%' resume 'brightnessctl --restore' timeout 360 '~/.config/hypr/scripts/sleep' before-sleep 'hyprlock'
#+end_src

** Hypridle
#+begin_src conf
exec-once = hypridle
#+end_src

** Polkit
Be careful to use the appropriate =polkit= and the right =path=
#+begin_src conf :tangle no
  # exec-once=/usr/lib/polkit-1/polkitd
#+end_src

#+begin_src conf
  exec-once=/usr/lib/polkit-kde-authentication-agent-1
#+end_src

** Wal
#+begin_src conf
exec-once = wal -R
#+end_src

** Network-Manager
Make sure you havc installed =network-manager-applet=
#+begin_src conf
exec-once = nm-applet --indicator
#+end_src

** Clipboard
#+begin_src conf
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data
#+end_src

** Gtk
#+begin_src conf :tangle no
exec-once = ~/.config/hypr/scripts/gtkthemes-bkp
#+end_src

** Hyprcursor
#+begin_src conf
exec-once = hyprctl setcursor Qogir-dark 24 #19
#+end_src

** Ghostty
#+begin_src conf
exec-once = ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false
#+end_src

* INPUT
Configure mouse and touchpad here
#+begin_src conf
  input {
      kb_layout = fr
      # kb_variant =
      # kb_model =
      # kb_options =
      # kb_rules =
      follow_mouse = 1
      numlock_by_default = 1

      touchpad {
          natural_scroll = no
          scroll_factor = 0.8
          # Use two-finger clicks for right-click instead of lower-right corner
          clickfinger_behavior = 1
      }

      # Sensitity for mouse/trackpack
      sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  }
#+end_src

* GENERAL
#+begin_src conf
  source = ~/.cache/wal/colors-hyprland.conf

  general {
      gaps_in = 5
      gaps_out = 10
      border_size = 2
      layout = master
      col.active_border = $color4 $color6 45deg
      col.inactive_border = $color8
      allow_tearing = false
      snap {
          enabled = true
      }
      resize_on_border = true
  }
#+end_src

* CURSOR
Make the cursor disappear after 3 seconds
#+begin_src conf
  cursor {
    inactive_timeout = 3
    enable_hyprcursor = true
  }
#+end_src

* GROUP
#+begin_src conf
  group {
      col.border_active = $color4 $color6 45deg
      col.border_inactive = $color8

      groupbar {
         render_titles = false
         gradients = true
         height = 4
         col.active = $color4
         col.inactive = $color0
      }
  }
#+end_src

* DECORATION
Decoration settings like Rounded Corners, Opacity, Blur, etc.

Your blur =amount= is =blur_size * blur_passes= , but high blur_size (over around 5-ish) will produce artifacts.
if you want heavy blur, you need to up the blur_passes.
the more passes, the more you can up the blur_size without noticing artifacts.

#+begin_src conf
  decoration {
      active_opacity = 0.90
      inactive_opacity = 0.90
      rounding = 0         # original 10
      # rounding_power = 2.0  # original 2.0
      blur {
          enabled = true
          new_optimizations = true
          size = 6   # minimum 1
          passes = 2 # minimum 1, more passes = more resource intensive.
      }
      shadow {
          enabled = false
          range = 8
          offset = 1 2
          scale = 0.97
          color = rgba(1E202966)
          color_inactive = 0x50000000
      }
      dim_inactive = true
      dim_strength = 0.05
  }
#+end_src

* RENDER
#+begin_src conf
  render {
      cm_enabled = true # default value
  }
#+end_src


* ANMATIONS
#+begin_src conf
  animations {
      enabled = yes

      bezier = easeOutQuint  ,0.23 ,1    ,0.32  ,1
      bezier = easeInOutCubic,0.65 ,0.05 ,0.36  ,1
      bezier = linear        ,0    ,0    ,1     ,1
      bezier = almostLinear  ,0.5  ,0.5  ,0.75  ,1.0
      bezier = quick         ,0.15 ,0    ,0.1   ,1

      bezier = fast          , 0   , 0.99, 0    , 0.99
      bezier = smooth        , 0.1 , 0.99, 0.29 , 1.1
      bezier = overshot      , 0.05,0.9  ,0.1   ,1.1

      animation = global         , 1 , 10  , default
      # animation = border         , 1 , 5.39, easeOutQuint
      animation = windows        , 1 , 4.79, easeOutQuint, gnomed
      animation = fadeIn         , 1 , 1.73, almostLinear
      animation = fadeOut        , 1 , 1.46, almostLinear
      animation = fade           , 1 , 3.03, quick
      animation = layers         , 1 , 3.81, easeOutQuint
      animation = layersIn       , 1 , 4   , easeOutQuint, slide
      animation = layersOut      , 1 , 1.5 , linear      , slide
      animation = fadeLayersIn   , 1 , 1.79, almostLinear
      animation = fadeLayersOut  , 1 , 1.39, almostLinear
      animation = workspaces     , 1 , 5   , overshot    , slide
  }
#+end_src

* DWINDLE
#+begin_src conf
dwindle {
    pseudotile = true
    preserve_split = true
    smart_split = false
}
#+end_src

* MASTER
#+begin_src conf
master {
    new_on_top = false
}
#+end_src

* GESTURE
#+begin_src conf
gestures {
    workspace_swipe = yes
    workspace_swipe_fingers = 3
    workspace_swipe_create_new = true
}
#+end_src

* MISC
#+begin_src conf
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = false
}
#+end_src

* WINDOW RULES
List of options
- windowrule = move 69 420,abc
- windowrule = size 420 69,abc
- windowrule = tile,xyz
- windowrule = pseudo,abc
- windowrule = monitor 0,xyz
- windowrule = workspace 12,abc
- windowrule = opacity 1.0,abc
- windowrule = animation slide left,abc
- windowrule = rounding 10,abc

#+begin_src conf
  # Float Necessary Windows
  windowrule = float,class:^waypaper$
  windowrule = float,class:^org.pulseaudio.pavucontrol$
  windowrule = float,class:^foot-float$
  windowrule = float,class:^nm-connection-editor$
  windowrule = float,class:^Gimp$
  windowrule = float,class:^blueman-manager$
  windowrule = float,class:^org.twosheds.iwgtk$
  windowrule = float,class:^blueberry.py$
  windowrule = float,class:^(xdg-desktop-portal-gtk|org.freedesktop.impl.portal.desktop.kde)$
  windowrule = center, class:^(org.freedesktop.impl.portal.desktop.kde)$
  windowrule = size 1280 720,class:^(org.freedesktop.impl.portal.desktop.kde)$

  windowrule = float,class:^org.kde.gwenview$
  windowrule = size 65% 65%,class:^org.kde.gwenview$

  windowrule = float,class:^kitty$ title:^(float-.*)$
  windowrule = size 50% 50%,class:^kitty$ title:^(float-.*)$

  windowrule = workspace 4,class:^Pop$

  # Gnome Settings
  windowrule = float,class:^(org.gnome.Settings)$
  windowrule = center,class:^(org.gnome.Settings)$
  windowrule = size 1280 720,class:^(org.gnome.Settings)$

  # Browser
  windowrule = workspace 2,class:^brave-browser$
  windowrule = workspace 2,class:^zen$
  windowrule = float,class:^(brave)$,title:^(Open File)$
  windowrule = float,class:^(brave)$,title:^(Save File)$
  windowrule = float,class:^(brave)$,title:^(Picture in picture)$
  windowrule = float,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = size 740 440,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = move onscreen 100%-w-20,class:^(zen)$,title:^(Picture-in-Picture)$
  windowrule = float,class:^brave-.*-Default$

  # Emacs
  windowrule = workspace 3,class:^(emacs)$

  # Message App
  windowrule = workspace 1,class:^(.*Microsoft Teams.*|teams-for-linux|discord|WebCord|Slack)$
  windowrule = workspace 1,class:^()$

  # All
  windowrule = opaque 1,class:^(.*)$
  windowrule = opaque 0,class:^(kitty|Alacritty|com.mitchellh.ghostty)$
#+end_src

* LAYERRULES
#+begin_src conf
layerrule = noanim, selection
layerrule = noanim, hyprpicker
layerrule = dimaround, rofi
#+end_src

* KEYBINDINGS
** Variable
#+begin_src conf
  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  $mainMod = SUPER

  $term = ghostty --gtk-single-instance=true
  $termapp = $term -e
  $term2 = kitty
  $wallpapermenu = ~/.config/rofi/wallpaper.sh
  $thememenu = ~/.config/rofi/theme.sh
  $appmenu = ~/.config/rofi/appmenu.sh
  $clipboardlist = ~/.config/rofi/clipboardlist.sh
  $powermenu = ~/.config/hypr/scripts/powermenu
  $volume = ~/.config/hypr/scripts/volume
  $notificationmenu = swaync-client -t
  $brightness = ~/.config/hypr/scripts/brightness
  $lockscreen = hyprlock
  $sleep = ~/.config/hypr/scripts/sleep
  $suspend = ~/.config/hypr/scripts/suspend
  $wlogout = ~/.config/hypr/scripts/wlogout
  $colorpicker = ~/.config/hypr/scripts/colorpicker
  $files = dolphin
  $editor = emacsclient -c -n -a 'emacs'
  $editor-everywhere = emacsclient --eval "(emacs-everywhere)"
  $browser = zen
  $help_keybind = ~/.config/hypr/scripts/show_keybind
#+end_src

** Terminal
#+begin_src conf
  bind = $mainMod, Return, exec, $term
  bind = $mainMod SHIFT, Return, exec, $term2
  bind = $mainMod CTRL, Return, exec, [float; size 50% 60%] $term2
#+end_src

** Apps
#+begin_src conf
  bind = $mainMod, E, exec, $files
  bind = $mainMod SHIFT, E, exec, $editor
  bind = $mainMod SHIFT, I, exec, $editor-everywhere
  bind = $mainMod SHIFT, W, exec, $browser
  bind = $mainMod, ccedilla, exec, $termapp k9s
  bind = $mainMod, m, exec, $termapp btop
#+end_src

** Rofi
#+begin_src conf
  bind = $mainMod, D, exec, $appmenu
  bind = $mainMod, X, exec, $powermenu
  bind = $mainMod, W, exec, $wallpapermenu
  bind = $mainMod, T, exec, $thememenu
  bind = $mainMod SHIFT, Comma, exec, pkill rofi || $help_keybind
#+end_src

** Misc
#+begin_src conf
bind = $mainMod, C, exec, $colorpicker
bind = CTRL ALT,L, exec, $suspend
#+end_src

** Some nice mouse binds
#+begin_src conf
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
#+end_src

** Function keys
- ~e~ flag is used to repeat cmd when hold
#+begin_src conf
binde = ,XF86MonBrightnessUp, exec, $brightness --inc
binde = ,XF86MonBrightnessDown, exec, $brightness --dec
binde = ,XF86AudioRaiseVolume, exec, $volume --inc
binde = ,XF86AudioLowerVolume, exec, $volume --dec
bind = ,XF86AudioMute, exec, $volume --toggle
bind = ,XF86AudioMicMute, exec, $volume --toggle-mic
bind = ,XF86AudioNext, exec, playerctl next
bind = ,XF86AudioPrev, exec, playerctl previous
bind = ,XF86AudioPlay, exec, playerctl play-pause
bind = ,XF86AudioStop, exec, playerctl stop
#+end_src

** Screenshots
#+begin_src conf
  bind = ,PRINT, exec, hyprshot -m region
  bind = SHIFT, PRINT, exec, hyprshot -m window
  bind = CTRL, PRINT, exec, hyprshot -m output
#+end_src

** Image To DrawApp
#+begin_src conf
  bind = $mainMod SHIFT, P, exec, grim -g "$(slurp)" - | swappy -f -
#+end_src

** Screencapture
#+begin_src conf
  bind = $mainMod CTRL, S, exec, ~/.config/hypr/scripts/screen-capture.sh
#+end_src

** Image To Text
#+begin_src conf
  bind = $mainMod SHIFT, T, exec, grim -g "$(slurp -d -c D1E5F4BB -b 1B232866 -s 00000000)" "tmp.png" && tesseract "tmp.png" - | wl-copy && rm "tmp.png"
#+end_src

** Status Bar
#+begin_src conf
  bind = $mainMod ALT, SPACE, exec, pkill -SIGUSR1 waybar
#+end_src

** Hyprland
#+begin_src conf
  bind = $mainMod, Q, killactive,
  bind = CTRL ALT, Delete, exit,
  bind = $mainMod, F, fullscreen, 2
  bind = $mainMod CTRL, F, fullscreen, 0
  bind = $mainMod SHIFT, F, fullscreen, 1
  bind = $mainMod, SPACE, togglefloating,
  bind = $mainMod SHIFT, SPACE, togglesplit, # dwindle
  bind = $mainMod, P, pseudo, # dwindle
  bind = $mainMod, O, exec, hyprctl dispatch setprop active opaque toggle
  bind = $mainMod CTRL, SPACE, pin
  bind = $mainMod, G, togglegroup
  bind = $mainMod SHIFT, C, exec, ~/.config/hypr/scripts/compactmode.sh
  bind = $mainMod, F1, exec, ~/.config/hypr/scripts/gamemode.sh
  bind = $mainMod ALT, apostrophe, exec, hyprctl keyword general:layout "$(hyprctl getoption general:layout | grep -q 'dwindle' && echo 'master' || echo 'dwindle')" #! @description: "Toggle between dwindle and master layout"; @windows;

  # Example special workspace (scratchpad)
  bind = $mainMod, S, togglespecialworkspace, magic
  bind = $mainMod SHIFT, S, movetoworkspace, special:magic
#+end_src

** End Active Session
#+begin_src conf
  bind = $mainMod, ESCAPE, exec, hyprlock
  bind = $mainMod SHIFT, ESCAPE, exec, systemctl suspend
  bind = $mainMod ALT, ESCAPE, exit,
  bind = $mainMod CTRL, ESCAPE, exec, reboot
  bind = $mainMod SHIFT CTRL, ESCAPE, exec, systemctl poweroff
#+end_src

** Window Split Ratio
#+begin_src conf
  bind = $mainMod CTRL, Minus, splitratio, -0.1
  bind = $mainMod CTRL, Equal, splitratio, 0.1
#+end_src

** Tab Cycle
To switch between windows in a floating workspace

#+begin_src conf
  bind = $mainMod, Tab, cyclenext,        # change focus to another window
  bind = $mainMod, Tab, bringactivetotop, # bring it to the top
#+end_src

** Focus
#+begin_src conf
  bind = $mainMod, H, movefocus, l
  bind = $mainMod, H, bringactivetotop

  bind = $mainMod, L, movefocus, r
  bind = $mainMod, L, bringactivetotop

  bind = $mainMod, K, movefocus, u
  bind = $mainMod, K, bringactivetotop

  bind = $mainMod, J, movefocus, d
  bind = $mainMod, J, bringactivetotop

  bind = $mainMod, Comma, focusmonitor, -1
  bind = $mainMod, Semicolon, focusmonitor, +1
#+end_src

** Move Window
#+begin_src conf
  bind = $mainMod SHIFT, H, movewindoworgroup, l
  bind = $mainMod SHIFT, L, movewindoworgroup, r
  bind = $mainMod SHIFT, K, movewindoworgroup, u
  bind = $mainMod SHIFT, J, movewindoworgroup, d
#+end_src

** Focus Group Window
#+begin_src conf
  bind = $mainMod, B, changegroupactive, b
  bind = $mainMod SHIFT, B, changegroupactive, f
#+end_src

** Resize Window
- 'e' flag is used to repeat cmd when hold
#+begin_src conf
  binde = $mainMod CTRL, H, resizeactive, -20 0
  binde = $mainMod CTRL, L, resizeactive, 20 0
  binde = $mainMod CTRL, K, resizeactive, 0 -20
  binde = $mainMod CTRL, J, resizeactive, 0 20
#+end_src

** Workspaces
*** Focus
#+begin_src conf
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute, workspace, 2
bind = $mainMod, quotedbl, workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft, workspace, 5
bind = $mainMod, minus, workspace, 6
bind = $mainMod, egrave, workspace, 7
bind = $mainMod, underscore, workspace, 8
#+end_src

*** Focus On Current Monitor
#+begin_src conf :tangle no
bind = $mainMod, ampersand, focusworkspaceoncurrentmonitor, 1
bind = $mainMod, eacute, focusworkspaceoncurrentmonitor, 2
bind = $mainMod, quotedbl, focusworkspaceoncurrentmonitor, 3
bind = $mainMod, apostrophe, focusworkspaceoncurrentmonitor, 4
bind = $mainMod, parenleft, focusworkspaceoncurrentmonitor, 5
bind = $mainMod, minus, focusworkspaceoncurrentmonitor, 6
bind = $mainMod, egrave, focusworkspaceoncurrentmonitor, 7
bind = $mainMod, underscore, focusworkspaceoncurrentmonitor, 8
#+end_src

*** Move workspace to different monitor
#+begin_src conf
bind=$mainMod ALT,h,movecurrentworkspacetomonitor,l
bind=$mainMod ALT,j,movecurrentworkspacetomonitor,p
bind=$mainMod ALT,k,movecurrentworkspacetomonitor,u
bind=$mainMod ALT,l,movecurrentworkspacetomonitor,r
#+end_src

*** Send to Workspaces
#+begin_src conf
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute, movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl, movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft, movetoworkspace, 5
bind = $mainMod SHIFT, minus, movetoworkspace, 6
bind = $mainMod SHIFT, egrave, movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
#+end_src

*** Scroll Through Existing Workspaces
#+begin_src conf
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod CTRL, mouse_up, workspace, +1
bind = $mainMod CTRL, mouse_down, workspace, -1
#+end_src

** Clipboard
#+begin_src conf
bind = SUPER, V, exec, $clipboardlist
#+end_src

** Zoom
#+begin_src conf
  bind = $mainMod SHIFT, mouse_down,exec,hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 + 0.5}')
  bind = $mainMod SHIFT, mouse_up,  exec,hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 - 0.5}')

  binde = $mainMod,       equal, exec,hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 + 0.5}')
  binde = $mainMod SHIFT, minus, exec,hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor | awk '/^float.*/ {print $2 - 0.5}')
  bind = $mainMod SHIFT,  equal,  exec,hyprctl -q keyword cursor:zoom_factor 1
#+end_src

** Notification
#+begin_src conf
bind = $mainMod, N, exec, $notificationmenu
#+end_src

* SCREEN-SHARING
#+begin_src conf
  env = GDK_BACKEND,wayland
  env = QT_QPA_PLATFORM,wayland
  env = XDG_CURRENT_DESKTOP,Hyprland
  env = XDG_SESSION_TYPE,wayland
  env = XDG_SESSION_DESKTOP,Hyprland
  env = QT_STYLE_OVERRIDE,kvantum
  env = SDL_VIDEODRIVER,wayland
  env = MOZ_ENABLE_WAYLAND,1
  env = ELECTRON_OZONE_PLATFORM_HINT,wayland
  env = OZONE_PLATFORM,wayland

  exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#+end_src

* DEFAUL_APPS
To activate default app for dolphin
#+begin_src conf
  env = XDG_MENU_PREFIX,arch-
#+end_src
