# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='#212337'
foreground='#c8d3f5'
cursor='#e0def4'

# Colors
color0='#222436'
color1='#ff5370'
color2='#c3e88d'
color3='#ff995e'
color4='#86e1fc'
color5='#baacff'
color6='#ff98a4'
color7='#e0def4'
color8='#2f334d'
color9='#ff757f'
color10='#77e0c6'
color11='#ff995e'
color12='#b4f9f8'
color13='#c099ff'
color14='#ff98a4'
color15='#e0def4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
